### ISSUE TITLE
When submitting an invalid transaction all nodes try to mine

### ISSUE THREAD

**Issue by lehmann-labs** [web3coach/the-blockchain-bar#12]
Given:
- Account with a certain balance
When:
 - Transaction value is higher then value hold in balance for the account
Then:
- All nodes try to mine the block, the first successful can not add the block to the chain (as transaction is invalid), all the other nodes continue mining.

Maybe it would be good to have some pre-mining validation of each transaction?

**Comment by web3coach** [comment]
Definitely! One of the exercises I planned to add for the students. Do you want to take on the opportunity and create a PR? It's an easy fix.

**Comment by web3coach** [comment]
Hi, Added the pre-mining validation. Good idea @lehmann-labs !

https://github.com/web3coach/the-blockchain-bar/commit/0bbbe3fcf955fa7d5c654844c9727b9a2e75ecb4
