### ISSUE TITLE
How can I buy your ebook?

### ISSUE THREAD

**Issue by vietvulong** [web3coach/the-blockchain-bar#13]
Hello, Lucac. I want to buy your ebook directly. Can I buy it through paypal?
Thanks.

**Comment by web3coach** [comment]
Hi @vietvulong, you definitely can.

Choose Paypal option at: https://gumroad.com/l/build-a-blockchain-from-scratch-in-go

**Comment by vietvulong** [comment]
Is it a PDF file? Can you send me the PDF to my email if I send the payment to your paypal directly?
