### ISSUE TITLE
Question about downloading

### ISSUE THREAD

**Issue by ValerieKenyon** [web3coach/the-blockchain-bar#18]
Hi, I'm interested in this tutorial, but I'm using Mac OS, not linux.  Is there a download option for Mac OS?

**Comment by web3coach** [comment]
Hi @ValerieKenyon , you have to compile it from your machine for Mac. Follow this tutorial for the first few chapters to set up the project locally: https://www.freecodecamp.org/news/build-a-blockchain-in-golang-from-scratch/
