### ISSUE TITLE
Go Modules & Book Review

### ISSUE THREAD

**Issue by dxps** [web3coach/the-blockchain-bar#2]
Hi Lukas,

Just downloaded the book sample from your web3.coach website, and I will look into it.

As I wanted to ask you on LinkedIn (but aparently you need Premium license to send a message (or it's too late in the night for me right now ... 😴), I am writing to you in this repo:
1. Since Go 1.14 is already for available for some time, why not just start using it and Go modules, instead of keep promoting usage of the old GOPATH mode?
2. About the book review, are you referring to what I just downloaded? Or the entire book you are planning to release in the near future? Either way, I would like to provide a review, if you are still interested.

Thanks.

**Comment by dxps** [comment]
Well, now I noticed that starting with `c3_...` branch you are using Go modules, so ignore the first question.

**Comment by web3coach** [comment]
Hi Marius!

Thanks for the questions.

1) :)
2) I already found several people who are doing the review of the full book but once you finish the first 6 chapters, I would be happy to hear your feedback! 

My email is in the last chapter, together with a short survey form
