### ISSUE TITLE
Chapter 11 Branch's TestNode_Run fails with memory leak

### ISSUE THREAD

**Issue by romuloctba** [web3coach/the-blockchain-bar#27]
Hi there, I am found a issue when following the book, and want to bring it to your attention here:

**_How it happened_**

As I got to the book's chapter 11, at page 301~304, there is this `TestNode_Run` test that is added, but locally, I could not make it pass.

I struggled with it for quite some time, because i was stubborn and tried to type the code all the way to here..... 
So I went trough each of the files again and again trying to figure out what I was doing wrong that the test was failing..... And didn't get it

Finally I gave up and cloned the repo, went to branch `c11_consensus` and.... the test failed exactly as my local hand-typed version!

Checking out branch `c12_crypto`, and on, it Passes fine.

**_The error_**

Here is the error I get when run the
`go test -timeout=0 -count=1 ./node -test.v -test.run ^TestNode_Run$` command:

```
--- FAIL: TestNode_Run (5.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x68f7ef]
```

**_Now What_**

Well, now I plan to check the diff between branches c11 and c12, hoping to figure out the problem before moving on to the next pages of the book. 

When I checked out the `c12_crypto` branch, and ran the test, I saw that many dependencies were added, so I figure there are lots of logic and new things going on.

Because on the book the test passes at this point, I really want to understand what is wrong before going on the new content.

- I created this issue because I know I will not have the will to do so after figuring out the problem.... 
- But I really think it is important to mention it here, so hopefully the code or the book can be fixed.

**Comment by web3coach** [comment]
Hi @romuloctba ! 

Thanks for reporting this. I am glad you are progressing in such a detail through the book.

I fixed the test. When you look in `c12_crypto` u will see I did a change where the HTTP server no longer returns error when closed gracefully but forgot to update the test... 

![Screenshot from 2022-02-26 17-50-30](https://user-images.githubusercontent.com/54218031/155851752-3f7818b2-bde2-4a7e-ad97-e6cae4ccc427.png)

This is fixed now and the test is passing again.

**Comment by romuloctba** [comment]
Thanks, @web3coach ! I bought the book this Feb 15th, and, since then, I am managing to study/read/code it almost every night until 3am (with breaks ofc) \o/

It takes longer than just reading it, but I feel like I learn better this way

Sometimes if get a little lost in the book examples, I just go to diffs between chapter branches, or check the "study code" commits you present at the end of each chapter.

I am learning a lot. Thank you

**Comment by web3coach** [comment]
That's exactly the way! Well done.
