### ISSUE TITLE
tbb version zsh: exec format error: tbb

### ISSUE THREAD

**Issue by Gauthami75** [web3coach/the-blockchain-bar#29]
Can you please help me . I am facing issue with the initial setup. I am using MacOs.

Thank you

**Comment by web3coach** [comment]
Hmm. Paste here please the full terminal input/output or a screenshot.

**Comment by Gauthami75** [comment]
![Terminal Screenshot ](https://user-images.githubusercontent.com/52778449/169695927-cf75f8f0-de1f-4297-88e1-087878d6e0d0.png)

**Comment by web3coach** [comment]
It seems to me like you are trying to run a Linux binary on Mac. Download the repo and compile the binary from source code itself.

**Comment by Gauthami75** [comment]
Thank you :)
