### ISSUE TITLE
Section 3 doesn't have data attribute

### ISSUE THREAD

**Issue by timdadd** [web3coach/the-blockchain-bar#6]
It's a great tutorial - I haven't got to the end - but will raise any issues as I go along for you
It says CLI is done and includes this line
```bash
tbb tx add --from=andrej --to=andrej --value=100 --data=reward
```
but the `-data` flag isn't in the code at that stage so an error

**Comment by web3coach** [comment]
Nice catch @timdadd . The flag must got lost when I was moving commits around. Fix commited to c3_ branch https://github.com/web3coach/the-blockchain-bar/commit/6601948305e91c2810169c0ac6e2b784d3d898ce
