### ISSUE TITLE
Add output of state JSON

### ISSUE THREAD

**Issue by timdadd** [web3coach/the-blockchain-bar#8]
At the beginning you show the balances in a JSON file.  So I added a simple additional command to do the same `tbb balances state`

```Go
var balancesStateCmd = &cobra.Command{
	Use:   "state",
	Short: "State of balances (json).",
	Run: func(cmd *cobra.Command, args []string) {
		state, err := dao.NewStateFromDisk()
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		defer state.Close()

		json, err := json.MarshalIndent(state, "", "  ")
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println(string(json))
	},
```

**Comment by web3coach** [comment]
Hi @timdadd, great you know how to hook into the state and display it in the format you like. One note on this, remember that in the chapters 8+ with HTTP state in place, the latest state should be queried from the HTTP API to avoid reading non-persistent state :)
