### ISSUE TITLE
Page 38 missing --data=reward flag

### ISSUE THREAD

**Issue by web3coach** [web3coach/the-blockchain-bar#9]
As reported by Paul on Discord:

![Screenshot from 2020-08-17 13-44-00](https://user-images.githubusercontent.com/54218031/90392745-bdf33800-e08f-11ea-956b-96250b24eb41.png)

**Comment by paulcockrell** [comment]
While you're modifying this section, it's worth noting that the third transaction in the example transactions `tbb tx add --from=babayaga --to=andrej --value=2000` has the `from` and `to` values the wrong way around. Andrej is paying Babayag 1000tbb+100% for joining.

**Comment by web3coach** [comment]
Eagle eye! Thanks for reporting. Indeed. On page 21 it's correct but then a mistake in copy pasting.

![Screenshot from 2020-08-17 13-54-48](https://user-images.githubusercontent.com/54218031/90393563-4c1bee00-e091-11ea-97aa-c96f48b5d578.png)

**Comment by web3coach** [comment]
Fixed. Will be released now in the new version with other fixes. Thanks for raising it up @paulcockrell
